#!/bin/bash
set -e

# gvenzl/oracle-free: APP_USER ja foi criado pela imagem com CONNECT + RESOURCE.
# Este script cria a tabela POSTS e insere seed data conectando como APP_USER no PDB.

APP_USER=${APP_USER:-"TEMPLATEBANKING_ADM"}
APP_PASS=${APP_USER_PASSWORD:-"adm"}

echo "=========================================="
echo "  Oracle 23ai Free — Schema Setup"
echo "=========================================="
echo "App user..........: ${APP_USER}"
echo "=========================================="

sqlplus -s "${APP_USER}/${APP_PASS}@//localhost:1521/FREEPDB1" <<EOF
SET ECHO ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- 1) Tabela POSTS com IDENTITY
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM   user_tables
  WHERE  table_name = 'POSTS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE POSTS (
        ID       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        TITLE    VARCHAR2(255)   NOT NULL,
        USER_ID  NUMBER(19)      NOT NULL,
        BODY     CLOB            NOT NULL,
        CONSTRAINT PK_POSTS PRIMARY KEY (ID)
      )
    ';
    dbms_output.put_line('Table POSTS created.');
  ELSE
    dbms_output.put_line('Table POSTS already exists. Skipping.');
  END IF;
END;
/

-- 2) Index em USER_ID (cenario B — busca por usuario)
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM   user_indexes
  WHERE  index_name = 'IDX_POSTS_USER_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_POSTS_USER_ID ON POSTS (USER_ID)';
    dbms_output.put_line('Index IDX_POSTS_USER_ID created.');
  ELSE
    dbms_output.put_line('Index IDX_POSTS_USER_ID already exists. Skipping.');
  END IF;
END;
/

-- 3) Seed data: 1000 posts distribuidos entre 50 usuarios
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM POSTS;
  IF v_count > 0 THEN
    dbms_output.put_line('Table POSTS already has data (' || v_count || ' rows). Skipping seed.');
  ELSE
    FOR i IN 1..1000 LOOP
      INSERT INTO POSTS (TITLE, USER_ID, BODY)
      VALUES (
        'Post Title #' || i,
        MOD(i - 1, 50) + 1,
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
          || 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
          || 'Post number ' || i || '.'
      );
    END LOOP;
    COMMIT;
    dbms_output.put_line('Inserted 1000 seed posts.');
  END IF;
END;
/

PROMPT >>> DONE.
EXIT;
EOF

echo "=========================================="
echo "Schema setup complete for ${APP_USER}"
echo "=========================================="